name: Release tiny-httpd

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version (e.g. v1.0.0)'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: tiny-httpd-linux
          - goos: darwin
            goarch: amd64
            output: tiny-httpd-mac-intel
          - goos: darwin
            goarch: arm64
            output: tiny-httpd-mac-arm
          - goos: windows
            goarch: amd64
            output: tiny-httpd-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build ${{ matrix.output }}
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.output }} tiny-httpd.go

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: dist/${{ matrix.output }}

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display structure
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          files: |
            dist/**/tiny-httpd-*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
